# Generated by Django 5.1.7 on 2025-03-17 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mod_perms_level', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mod_in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.moderator')),
                ('original_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('mod_in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.moderator')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('mod_in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.moderator')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.resource')),
            ],
        ),
    ]
